FROM geodata/gdal
MAINTAINER Nathan <nathan.suberi@wri.org>

ENV PYTHON_VERSION 2.7.11
ENV PYTHON_PIP_VERSION 8.0.2
ENV NUM_CORES 4

RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 

RUN apt-get -qq remove ffmpeg
# remove several traces of python
RUN apt-get purge -y python.*

# Add the following two dependencies if you want to use --enable-gnutls in FFPMEG: gnutls-bin
RUN echo deb http://archive.ubuntu.com/ubuntu trusty universe multiverse >> /etc/apt/sources.list; \
    apt-get update -qq && apt-get install -y --force-yes \
    ant \
    autoconf \
    automake \
    build-essential \
    curl \
    checkinstall \
    cmake \
    default-jdk \
    f2c \
    gfortran \
    git \
    g++ \
    imagemagick \
    libass-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libcnf-dev \
    libfaac-dev \
    libfreeimage-dev \
    libjpeg-dev \
    libjasper-dev \
    libgnutls-dev \
    liblapack3 \
    libmp3lame-dev \
    libpq-dev \
    libpng-dev \
    libssl-dev \
    libtheora-dev \
    libtiff4-dev \
    libtool \
    libxine-dev \
    libxvidcore-dev \
    libv4l-dev \
    libvorbis-dev \
    mercurial \
    openssl \
    pkg-config \
    postgresql-client \
    supervisor \
    wget \
    unzip; \
    apt-get clean

# gpg: key 18ADD4FF: public key "Benjamin Peterson <benjamin@python.org>" imported
ENV GPG_KEY C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF

RUN set -ex \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEY" \
	&& curl -fSL "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tar.xz" -o python.tar.xz \
	&& curl -fSL "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tar.xz.asc" -o python.tar.xz.asc \
	&& gpg --verify python.tar.xz.asc \
	&& mkdir -p /usr/src/python \
	&& tar -xJC /usr/src/python --strip-components=1 -f python.tar.xz \
	&& rm python.tar.xz* \
	&& cd /usr/src/python \
	&& ./configure --enable-shared --enable-unicode=ucs4 \
	&& make -j$(nproc) \
	&& make install \
	&& ldconfig \
	&& curl -fSL 'https://bootstrap.pypa.io/get-pip.py' | python2 \
	&& pip install --no-cache-dir --upgrade pip==$PYTHON_PIP_VERSION \
	&& find /usr/local \
		\( -type d -a -name test -o -name tests \) \
		-o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
		-exec rm -rf '{}' + \
	&& rm -rf /usr/src/python

# install "virtualenv", since the vast majority of users of this image will want it
RUN pip install --no-cache-dir virtualenv


ARG NAME=python-script
ENV NAME ${NAME}

RUN apt-get update && \
   apt-get install -y \
   bash \
   git \
   openssl \
   build-essential \
   libffi-dev \
   libxml2 \
   libxslt-dev \
   cron

# Set user to root explicitly (would be anyway by default)
USER root


### Need to be a root to do these steps? ###
## Install netcdf tools
COPY install_ntcdf4.sh /opt/install_ntcdf4.sh
RUN ls /opt
RUN /opt/install_ntcdf4.sh

## This is now happening in the base image
# Install gdal
#COPY before_install.sh.patch /usr/local/src/gdal-docker/
#COPY build.sh /usr/local/src/gdal-docker/
#COPY install.sh.patch /usr/local/src/gdal-docker/
#RUN /usr/local/src/gdal-docker/build.sh

# Create non-root user to limit permissions
RUN groupadd -r $NAME && useradd -r -g $NAME $NAME

# Install pip, use to download any needed python packages...
## Why is virtualenv not included as part of requirements.txt?
RUN easy_install pip && pip install --upgrade pip
RUN pip install virtualenv


RUN mkdir -p /opt/$NAME
COPY requirements.txt /opt/$NAME/requirements.txt
RUN cd /opt/$NAME && pip install -r requirements.txt

# main.py launches the dataset specific code, contained in the /src directory
### Why not have the code directly in main.py??
COPY main.py /opt/$NAME/main.py


# Copy the application folder inside the container
WORKDIR /opt/$NAME

## Contains data set specific code
COPY ./src /opt/$NAME/src
## Is this needed? Only if there is data we're going to work with...
# COPY ./data /opt/$NAME/data

# Assign correct permissions to user/group to modify files in /opt/$NAME
RUN chown $NAME:$NAME /opt/$NAME
# Set user with limited permissions
USER $NAME


# Setting volume explicitly here forces the creation of the Volume directory, regardless of whether user maps a host directory to this volume using -v HOST_DIR:/opt/$NAME/data

VOLUME /opt/$NAME/data


# Launch script
CMD ["python", "main.py"]